### ISSUE TITLE
Using the ~ operator is causing some charts to overreport the number of crashes

### ISSUE THREAD

**Issue by marco-c** [ashughes1/bugzilla-socorro-lens#14]
For example, if you load `chart.htm?s=JS::Heap<T>::~Heap<T>`, the Socorro query is `https://crash-stats.mozilla.com/api/SuperSearch/?signature=~JS::Heap%3CT%3E::~Heap%3CT%3E&date=%3E%3D2016-03-23&date=%3C%3D2016-09-18&_histogram.date=_cardinality.install_time&_histogram_interval=1d&_results_number=0`, which means you'll get results for three signatures (`JS::Heap<T>::~Heap<T>`, `shutdownhang | JS::Heap<T>::~Heap<T>`, `js::HashSet<T>::remove | JS::Heap<T>::~Heap<T>`) instead of just the one you wanted (`JS::Heap<T>::~Heap<T>`).

**Comment by ashughes1** [comment]
Marco, I think I should merge this with issue 17.

To clarify, this is not a bug in engineering but that of a design decision. Basically what it comes down to is choosing between searching for _signature equals_ or _signature contains_. The side effect of choosing _equals_ is potentially under-reporting crash volume since you'd be missing related signatures not listed in the bug report. The side effect of choosing _contains_ is potentially over-reporting crash volume since you'd be aggregating unrelated crashes with similar signatures.

My thinking is that over-reporting poses less of a risk to Firefox/Thunderbird/Fennec users than under-reporting and so that is why I opted to use _contains_ instead of _equals. However, upon further consideration I am toying with the idea of adding the ability to show both on the chart and being able to toggle either on and off.

For now I am not going to merge pull request 15 but I would like to get your thoughts on this matter.

**Comment by marco-c** [comment]
It makes sense. It's hard to decide between the two (`contains` vs `equals`), I can't think of a good UI for this. Perhaps your toggling idea might be feasible.

**Comment by ashughes1** [comment]
@marco-c you should be able to flip between exact (=) and like (~) matches now, although I'll keep the default to like (~). When you test it you'll need to look at the actual numbers. I was testing with the signature you mentioned above but the difference in numbers is too small to show visually on the chart.

Test it out and let me know what you think.

**Comment by marco-c** [comment]
Thanks, this is really useful. Perhaps the wording can be improved for people who are less familiar with searching on Socorro, but I'm not sure how to do that (maybe "Find crashes with exact signature" and "Find crashes with similar signature", but they are quite long).

**Comment by ashughes1** [comment]
> Perhaps the wording can be improved for people who are less familiar with searching on Socorro

Thanks for the feedback. It's a fair point but I suspect there are not many (if any) active users of this add-on who are unfamiliar with searching in Socorro. I'll have to look in to that.
