### ISSUE TITLE
Wrong chart shown in bug 1304566

### ISSUE THREAD

**Issue by philipp-sumo** [ashughes1/bugzilla-socorro-lens#16]
in bug 1304566 with the crash signature mozilla::dom::quota::QuotaManager::ShutdownObserver::Observe a graph with a pattern different to the actual signature is shown with the addon.

screenshot: http://i.imgur.com/zjqdgcv.png
socorro graph: https://crash-stats.mozilla.com/signature/?date=%3E%3D2016-06-01&signature=mozilla%3A%3Adom%3A%3Aquota%3A%3AQuotaManager%3A%3AShutdownObserver%3A%3AObserve#graphs

**Comment by ashughes1** [comment]
This is because the Socorro graph only counts crashes *exactly* matching the signature (ie. &signature=...) whereas BSL aggregates similar signatures (ie. &signature=~...). It's designed this way to measure total volume for an issue, particularly in cases where a single issue might be spread across multiple similar signatures.

In the case of bug 1304566 take a look at https://crash-stats.mozilla.com/search/?date=%3E%3D2016-06-01&signature=~mozilla%3A%3Adom%3A%3Aquota%3A%3AQuotaManager%3A%3AShutdownObserver%3A%3AObserve. As you can see, mozilla::dom::quota::QuotaManager::ShutdownObserver::Observe has 5112 crashes across 21 different signatures versus 347 crashes with 1 signature using your query. 

By looking at just one signature you might not be seeing the entire scope of an issue. In this case your query only represents 7% of the crash volume. 

_By the way, these other signatures should probably be added to that bug report._
