### ISSUE TITLE
Graph fails to load if the signatures list is too long (eg. https://bugzil.la/1229252)

### ISSUE THREAD

**Issue by calixteman** [ashughes1/bugzilla-socorro-lens#6]

**Comment by ashughes1** [comment]
Thanks for reporting this issue. I looked in to it and since there are so many signatures in this bug the URL generated is too long for Socorro, resulting in a 502 server-side error. I suppose one way to work around this would be to split the signatures into multiple API calls of no more than 10 signatures then aggregate the numbers from each call.

**Comment by calixteman** [comment]
Normally 10 is ok. I made several thousands queries with 10 signatures and never had any issues.

**Comment by ashughes1** [comment]
This should work now if you use the v0.5 unsigned addon xpi file from the addon folder in this repository. 

As suggested earlier I split the API calls into no more than 10 signatures at a time. Note that this limitation also exists on the SuperSearch report view so clicking a datapoint now opens a tab per 10 signatures. After much consideration this is the best way I thought it could be done. If you have a different idea then please submit it to this issue.

Please give it a try and let me know how it works for you.
